<?php 
	$isShowDescription = $this->showDescription(); 
	$productType = $this->getProductsType();
	$productCollection = $this->getProductCollection();
	$collectionSize = count($productCollection);
	//print_r($this);
	
	// $link is url to view all product page
	$link = $this->getBaseUrl();
	$link .= 'productlisting/';
	$link .= $productType;
?>

<?php if($collectionSize > 0):?>
<script type="text/javascript">
     $tab(document).ready(function(){
		$tab('#best-seller').bxSlider({
		  displaySlideQty: 3,
		  moveSlideQty: 1
		});
     });
</script>
<div class="best-seller-product-content">
	<?php $_collectionSize = $productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
	<ul class="products-grid" id="best-seller">
    <?php $i=0; foreach ($productCollection as $_product): ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
				<div class="li-content">
					<a href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-zoom-image-best-seller product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270,182); ?>" width="270" height="182" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
					<a href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-zoom-colorbox-best-seller"><?php echo $this->htmlEscape($_product->getName()) ?></a>
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName() ?></a></h2>
					<?php //if($_product->getRatingSummary()): ?>
					<?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
					<?php //endif; ?>
					<?php echo $this->getPriceHtml($_product, true) ?>
					<!--<div class="actions">
						<?php if($_product->isSaleable()): ?>
							<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
						<ul class="add-to-links">
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
								<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
							<?php endif; ?>
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
							<?php endif; ?>
						</ul>
					</div>-->
				</div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        <?php endif ?>
        <?php endforeach ?>
		</ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
</div>


<?php else: ?>
<div class="note-msg">
	<?php echo $this->__('There are no products matching the selection.') ?>
</div>
<?php endif; ?>
<script>
	//var $colorbox = jQuery.noConflict();
	$tab(document).ready(function(){
		//Examples of how to assign the ColorBox event to elements
		$tab(".product-zoom-colorbox-best-seller").colorbox({rel:'product-zoom-colorbox-best-seller'});
		$tab(".product-zoom-image-best-seller").colorbox({rel:'product-zoom-image-best-seller'});
	});
</script>
