<?php 
	$isShowDescription = $this->showDescription(); 
	$productType = $this->getProductsType();
	$productCollection = $this->getProductCollection();
	$collectionSize = count($productCollection);
	//print_r($this);
	
	// $link is url to view all product page
	$link = $this->getBaseUrl();
	$link .= 'productlisting/';
	$link .= $productType;
?>

<?php if($collectionSize > 0):?>

			<script type="text/javascript">	
				var $k = jQuery.noConflict();
				$k(document).ready(function(){
						var widthwd = $k(window).width();
						/* alert(widthwd); */
						var widthSl;
						var minSl = 1;
						
							if(widthwd > 580){
								minSl = 2;
								widthSl= widthwd/2;
								
							}
					
						$k('#special-products').bxSlider({
							maxSlides:2,
							moveSlides:minSl,
							minSlides:minSl,
							slideWidth: widthSl,
							slideMargin: 11,
							preloadImages: 'visible', 
							pager:false,
							controls:true
						});
						
				});

				</script>
		
<script type="text/javascript">
	var $specialproduct = jQuery.noConflict();
		$specialproduct(document).ready(function(){
		
		  $specialproduct(".product-info-content", this).stop().animate({opacity:'0'});
			
		  $specialproduct('.item .product-info').live('mouseout', function(){
				$specialproduct(".product-info-content", this).stop().animate({opacity:'0'});
			}); 

			$specialproduct('.item .product-info').live('mouseover', function(){
				$specialproduct(".product-info-content", this).stop().animate({opacity:'0.9'});   
			});

			
		}); 
</script>

<div class="special-product-container">
	<h2 class="subtitle"><?php echo $this->__('Special Products') ?></h2>
	<div class="special-product-content">
		<?php $_collectionSize = $productCollection->count() ?>
		<?php $_columnCount = 4; ?>
			<?php if ($i++%$_columnCount==0): ?>
			<!--ul class="new-special-products-grid special-products-grid" id="special-products"-->
			<ul class="products-grid" id="special-products">
			<?php endif ?>
			<?php $i=0; foreach ($productCollection as $_product): ?>
				<li class="item">
					<div class="item-content">
					  <div class="product-image">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-zoom-image-special"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300,252); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
						<div class="product-info">
							<div class="product-info-content">
								<div class="desc std">
									<?php $_description = nl2br($this->htmlEscape($_product->getShortDescription()))?>
									<?php $short_desc = substr($_description, 0, 75);  ?>
									<?php if(substr($short_desc, 0, strrpos($short_desc, ' '))!='') $short_desc = substr($short_desc, 0, strrpos($short_desc, ' '));$short_desc = $short_desc.'...'; ?>
									<?php echo $short_desc;?>
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
								</div>
								<div class="rating-links">
									<?php if($_product->getRatingSummary()): ?>
									<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
									<?php endif; ?>
									<ul class="add-to-links">
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
										<?php endif; ?>
										<?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
											<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
										<?php endif; ?>
									</ul>
								</div>
							</div>
							<div class="btn-hover">&nbsp;</div>
						</div>
						</div>
						<div class="product_info">
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName() ?></a></h2>
						</div>
						
						<div class="price-actions">
							<?php echo $this->getPriceHtml($_product, true) ?>
							<div class="actions">
								<?php if($_product->isSaleable()): ?>
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
								<?php else: ?>
									<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
								<?php endif; ?>
							</div>
						</div>
					</div>
					<div class="sale">&nbsp;</div>
				</li>
			<?php endforeach ?>
			<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
			</ul>
			<?php endif ?>
			
			<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
	</div>


	
</div>

	<?php else: ?>
	<div class="note-msg">
		<?php echo $this->__('There are no products matching the selection.') ?>
	</div>

<?php endif; ?>