<?php
/**
 * Magento
 * @copyright   Copyright ( c ) 2013 www.magebuzz.com
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
	<div class="product-essential">
		<div class="product-essential-content">
				<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

				<div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>
				
        <div class="product-shop">
			<div class="top-product-shop-view">
				<div class="product-name">
					<h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
				</div>
				<div class="top-product-shop-content">
					<?php echo $this->getChildHtml('alert_urls') ?>
					<?php echo $this->getChildHtml('product_type_data') ?>
					<?php echo $this->getChildHtml('extrahint') ?>
					<?php echo $this->getTierPriceHtml() ?>
				</div>
			</div>
			<div class="social-network">
				<?php if ($this->canEmailToFriend()): ?>
					<p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
				<?php endif; ?>
				<?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
				<ul>
					<li class="fb-like">
						<script type="text/javascript">
						//<![CDATA[
							document.write('<iframe src="//www.facebook.com/plugins/like.php?href=<?php echo $_product->getProductUrl() ?>&amp;send=false&amp;layout=button_count&amp;width=70&amp;show_faces=true&amp;font&amp;colorscheme=light&amp;action=like&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:70; height:21px;" allowTransparency="true"></iframe>');
						//]]>
						</script> 
					</li>
					<li class="twitter-like">
						<iframe scrolling="no" frameborder="0" style="width:95px; height:20px;" src="http://platform0.twitter.com/widgets/tweet_button.html?url=http://www.magebuzz.com/&amp;text=&amp;counturl=http://www.magebuzz.com/" allowtransparency="true"></iframe>
					</li>
					<li class="google-plus">
						<g:plusone size="medium" href="<?php echo $_product->getProductUrl() ?>"></g:plusone>
						<script type="text/javascript">
							(function() {
							var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
							po.src = 'https://apis.google.com/js/plusone.js';
							var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
							})();
						</script>
					</li>
				</ul>
			</div>
			<?php if (!$this->hasOptions()):?>
				<div class="add-to-box">
					<?php if($_product->isSaleable()): ?>
						<?php echo $this->getChildHtml('addtocart') ?>
						<?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
							<span class="or"><?php echo $this->__('') ?></span>
						<?php endif; ?>
					<?php endif; ?>
					<?php echo $this->getChildHtml('addto') ?>
				</div>
				<?php echo $this->getChildHtml('extra_buttons') ?>
			<?php elseif (!$_product->isSaleable()): ?>
				<div class="add-to-box">
					<?php echo $this->getChildHtml('addto') ?>
				</div>
			<?php endif; ?>

			<?php if ($_product->getShortDescription()):?>
				<div class="short-description">
					<h2><?php echo $this->__('Quick Overview') ?></h2>
					<div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
				</div>
			<?php endif;?>

			<?php echo $this->getChildHtml('other');?>

			<?php if ($_product->isSaleable() && $this->hasOptions()):?>
				<?php echo $this->getChildChildHtml('container1', '', true, true) ?>
			<?php endif;?>

        </div>

        

        <div class="clearer"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
		</div>
	</div>
	<div class="product-info-tab-container">
		<div class="product-info-tab">
			<div class="tab-head">
				<ul class="tabs">
					<li class="first"><a href="#tab-description"><span><span><?php echo $this->__('Detail')?></span></span></a></li>
					<li><a href="#tab-additional"><span><span><?php echo $this->__('Additional Information')?></span></span></a></li>
					<li class="product-review" id="product-review"><a href="#tab-reviews-products"><span><span><?php echo $this->__('Reviews')?></span></span></a></li>
					<li class="last product-tag"><a href="#tab-product-tag"><span><span><?php echo $this->__('Product Tag')?></span></span></a></li>
				</ul>
			</div>
			<div class="tab_container">
				<div id="tab-description" class="tab_content">
					<?php echo $this->getChildHtml('description') ?>
				</div>
				<div id="tab-additional" class="tab_content">
					<?php echo $this->getChildHtml('additional') ?>				
				</div>
				<div id="tab-reviews-products" class="tab_content">
					<?php echo $this->getChildHtml('product_reviews') ?>
				</div>
				<div id="tab-product-tag" class="tab_content">
					<?php echo $this->getLayout()->createBlock('tag/product_list')->setTemplate('tag/list.phtml')->toHtml();?>
				</div>
			</div>	
		</div>
	</div>
	
	
    <!--div class="product-collateral">
	<?php //foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <div class="box-collateral <?php //echo "box-{$alias}"?>">
            <?php //if ($title = $this->getChildData($alias, 'title')):?>
            <h2><?php //echo $this->escapeHtml($title); ?></h2>
            <?php //endif;?>
            <?php //echo $html; ?>
        </div>
	<?php //endforeach;?>
        <?php //echo $this->getChildHtml('upsell_products') ?>
        <?php //echo $this->getChildHtml('product_additional_data') ?>
    </div-->
</div>
