<?php
/**
 * Magento
 *
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="main-container col2-right-layout">
            <div class="main container">
						    
                <?php echo $this->getChildHtml('breadcrumbs') ?>
								<div class="row">
										<div class="main-content">
												<div class="col-main col-md-9">
													<?php echo $this->getChildHtml('global_messages') ?>
													<?php echo $this->getChildHtml('content') ?>
												</div>
												<div class="col-right sidebar col-md-3"><?php echo $this->getChildHtml('right') ?></div>
										</div>
								</div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
