<?php
/**
 * Magento
 * @copyright   Copyright ( c ) 2013 www.magebuzz.com
 */

/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
	  $_gallery = $this->getGalleryImages();
   
?>


<script type="text/javascript">
function slide(url,num,gallery){
    if (typeof slide.loading == 'undefined') slide.loading = false;
	if(slide.loading) return false;

	var loader = new Image();
	$(loader).observe('load', function(){

		$('slide-loader').setStyle({'visibility':'hidden'});
		
		$$('div.more-views li').each(function(el,i){
			(i==num) ? el.addClassName('slide-current') : el.removeClassName('slide-current');
		});

		var dummy = new Element('img', { src: url }).setOpacity(0);
		new Insertion.After('image', dummy);
		new Effect.Opacity(dummy, { duration:.5, from:0, to:1.0 });
		new Effect.Opacity($('image'), { duration:.5, from:1.0, to:0, 
			 afterFinish: function(){
			 	$('image').writeAttribute('src',url).setOpacity(1);
			 	$('imagezoom').writeAttribute('src',url).setOpacity(1);
			 	$('imagezoomlink').writeAttribute('href',url);
			 	dummy.remove();
			 	slide.loading = false;
			 }
		});
	});

	$('slide-loader').setStyle({'visibility':'visible'});
	loader.src=url;
	slide.loading = true;
return false;
}
</script>
<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery('.fancybox').fancybox();
	});
</script>



		
<p class="product-image product-image-zoom">
   <a id="imagezoomlink" href="<?php echo $this->helper('catalog/image')->init($_product, 'image');?>" data-toggle="lightbox" class="fancybox" >
    <?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
				$imgzoom = '<img id="imagezoom" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
    </a>
		<img id="slide-loader" class="jqzoom slide-loader" src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" />
	</p>
	<div style="display:none;">
		<?php echo $_helper->productAttribute($_product, $imgzoom, 'image');?>
	</div>
	


<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
	<?php $_columnCount = 3; ?>
	<?php $i = 0; foreach ($this->getGalleryImages() as $_image):?>
	<?php if ($i++%$_columnCount==0): ?>
	<ul>
	<?php endif ?>
        <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>" id="image-morviews">
            <a rel="{gallery: 'imagefullsize', smallimage: '<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($_resize) ?>', largeimage: '<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())?>'}" href="javascript:void(0)" onclick="slide('<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_resize) ?>',<?php echo ($s = isset($s) ? ++$s : 0) ?>,'<?php echo $this->getGalleryUrl($_image) ?>'); return false;"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(80); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
        </li>
				
		<?php if ($i%$_columnCount==0 || $i==count($this->getGalleryImages())): ?>
    </ul>
	<?php endif ?>
	<?php endforeach; ?>
</div>
<?php endif; ?>